# Generated by Django 3.2.12 on 2022-03-04 22:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=home.models.Post.generate_filename),
        ),
    ]
